### ISSUE TITLE
Use @EVAL and mm_rules moveFieldsToTab

### ISSUE THREAD

**Issue by fourroses666** [Nicola1971/GooglePreviewTv#5]
When I change this;
`@INCLUDE/assets/tvs/googlepreview/googlepreview.customtv.php`

Into this;
`@EVAL: global $modx; return $modx->runSnippet('GooglePreview');`

I don't need a .php file anymore.
Just place the .php content into the snippet.

But mm_rule move to tab stops working.
```
mm_createTab('SEO', 'seo', '', '', '', '100%');
mm_moveFieldsToTab('GooglePreview', 'seo');
```

**Comment by fourroses666** [comment]
@Nicola1971 

I have changed;
<input type='text' style=\"display:none;\" id=\"tv$rid\" name=\"tv$rid\" value=\"tv$rid\" />

into;
<input type='text' style=\"display:none;\" id=\"tv$id\" name=\"tv$id\" value=\"tv$id\" />

And then it moves to the tab :0


```
$output .="
<div>
<input type='text' style=\"display:none;\" id=\"tv$id\" name=\"tv$id\" value=\"tv$id\" />
<style>
.s-google{background:#fff; width:100%; max-width:600px; margin-bottom:15px; font-family:arial,sans-serif; color:#545454; line-height:1.4; word-wrap:break-word; text-align:left; font-weight:normal; padding:15px; -webkit-box-shadow:0 0 6px 0 rgba(0,0,0,0.1); -moz-box-shadow:0 0 6px 0 rgba(0,0,0,0.1); box-shadow:0 0 6px 0 rgba(0,0,0,0.1);}
.s-google span{display:block;}
.s-titl{color:#1a0dab; white-space:nowrap; font-size:18px; line-height:1.5; font-weight:normal; text-decoration:none;}
.s-url{color:#006621; font-style:normal; font-size:14px; line-height:1.5; white-space:nowrap;}
.s-desc{font-size:13px;}
</style>
<div class=\"s-google\">
  <span class=\"s-titl\">$title</span>
  <span class=\"s-url\">$url</span>
  <span class=\"s-desc\">$description</span>
</div>
</div>";  
```

**Comment by fourroses666** [comment]
Oke, don't know why but on an other domain I can't move it to a tab somehow.
The preview works but can't move it. Really don't get it..

**Comment by fourroses666** [comment]
When I inspect the top TV in the tab I want to place the GooglePreview I see <input name="tv85"
When I manually add this to the Snippet it shows the GooglePreview on top in the tab.

Its weird but works..

**Comment by Nicola1971** [comment]
@fourroses666 
I never used in that way, sorry. I have to do some tests.
